#!/bin/bash -e

args=("$@")
MODE=${args[0]}
cd "$(dirname "$0")"

git fetch origin develop --quiet
CURRENT_REV=$(git rev-list HEAD --count)
HEAD_REV=$(git rev-list origin/develop --count)

echo "---------------------------------------------------"
echo "AVAILABLE REVISION: $CURRENT_REV"
echo "INSTALLED REVISION: $HEAD_REV"
echo "---------------------------------------------------"

if [ "$CURRENT_REV" == "$HEAD_REV" ]; then
    echo "No Update Available"
    exit
else
    echo "An Update Is Available"
fi

echo "---------------------------------------------------"
echo "UPDATES"
echo "---------------------------------------------------"
git log HEAD..origin/develop --format=oneline

echo "---------------------------------------------------"
echo "CHANGED FILES"
echo "---------------------------------------------------"

git --no-pager diff --stat --no-color HEAD..origin/develop

if [ "$MODE" != "--execute" ]; then
    echo "---------------------------------------------------"
    echo "update has NOT been performed. Use the --execute flag to do so"
    echo "---------------------------------------------------"
else
    echo "---------------------------------------------------"
    echo "stopping service iot-client"
    echo "---------------------------------------------------"
    pm2 stop iot-client

    echo "---------------------------------------------------"
    echo "in directory"
    echo "---------------------------------------------------"
    pwd

    echo "---------------------------------------------------"
    echo "deleting old staging dir"
    echo "---------------------------------------------------"
    rm -rf staging_dir

    echo "---------------------------------------------------"
    echo "cloning current repo"
    echo "---------------------------------------------------"
    git clone https://github.com/d89/IoT-raspberry.git staging_dir
    chmod +x staging_dir/actors/*
    chmod +x staging_dir/sensors/*
    chmod +x staging_dir/update

    echo "---------------------------------------------------"
    echo "making live"
    echo "---------------------------------------------------"
    rsync -Ea staging_dir/ .

    echo "---------------------------------------------------"
    echo "installing node modules"
    echo "---------------------------------------------------"
    cd client
    npm install

    echo "---------------------------------------------------"
    echo "setting access rights"
    echo "---------------------------------------------------"
    chown -R pi ..

    echo "---------------------------------------------------"
    echo "restarting service iot-client"
    echo "---------------------------------------------------"
    pm2 start iot-client

    echo "---------------------------------------------------"
    echo "update successfully done"
    echo "---------------------------------------------------"
fi