#!/usr/bin/python
from displaydriver import lcddriver
from time import *
import sys

lcd = lcddriver.lcd()

if (len(sys.argv) >= 2):
    lcd.lcd_display_string(sys.argv[1], 1)
if (len(sys.argv) >= 3):
    lcd.lcd_display_string(sys.argv[2], 2)
if (len(sys.argv) >= 4):
    lcd.lcd_display_string(sys.argv[3], 3)
if (len(sys.argv) >= 5):
    lcd.lcd_display_string(sys.argv[4], 4)
