#!/usr/bin/python
#Bibliotheken einbinden
import RPi.GPIO as GPIO
import time
import datetime
import json
import sys

#GPIO Modus (BOARD / BCM)
GPIO.setmode(GPIO.BOARD)

#GPIO Pins zuweisen
GPIO_TRIGGER = 31
GPIO_ECHO = 29

#Richtung der GPIO-Pins festlegen (IN / OUT)
GPIO.setup(GPIO_TRIGGER, GPIO.OUT)
GPIO.setup(GPIO_ECHO, GPIO.IN)

def distanz():
	# setze Trigger auf HIGH
	GPIO.output(GPIO_TRIGGER, True)

	# setze Trigger nach 0.01ms aus LOW
	time.sleep(0.00001)
	GPIO.output(GPIO_TRIGGER, False)

	StartZeit = time.time()
	StopZeit = time.time()

	# speichere Startzeit
	while GPIO.input(GPIO_ECHO) == 0:
		StartZeit = time.time()

	# speichere Ankunftszeit
	while GPIO.input(GPIO_ECHO) == 1:
		StopZeit = time.time()

	# Zeit Differenz zwischen Start und Ankunft
	TimeElapsed = StopZeit - StartZeit
	# mit der Schallgeschwindigkeit (34300 cm/s) multiplizieren
	# und durch 2 teilen, da hin und zurueck
	distanz = (TimeElapsed * 34300) / 2

	return distanz

if __name__ == '__main__':
	try:
		json_template = { 'distance': 0, 'time': str(datetime.datetime.now().time()) }

		while True:
			abstand = float("{0:.2f}".format(distanz()))

			json_template['distance'] = abstand
			json_template['time'] = str(datetime.datetime.now().time())

			print json.dumps(json_template)
			sys.stdout.flush()

			time.sleep(2.5)

	except KeyboardInterrupt:
		GPIO.cleanup()