#!/usr/bin/python
# Info - This program is for PIN sensor. Contionusly checks for state,
#        set LED if movement detected and plays wav file on detection.

import RPi.GPIO as GPIO
import time
import datetime
import json
import sys

PIN = 36
val = False
json_template = { 'state': 0, 'time': str(datetime.datetime.now().time()) }

GPIO.setmode(GPIO.BOARD)	# Change this if using GPIO numbering
GPIO.setup(PIN, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)	# Set PIN as input

try:
	while True:
		val = GPIO.input(PIN)

		if (val == False):
			json_template['state'] = 1
		else:
			json_template['state'] = 0

		json_template['time'] = str(datetime.datetime.now().time())

		print json.dumps(json_template)
		sys.stdout.flush()
		time.sleep(2)
finally:                   # run on exit
    GPIO.cleanup()         # clean up
