#!/usr/bin/python
from acdcdriver import pcf8591 as ADC
import time
import json
import sys
import datetime

#channel 0 = 0x40 = light
#channel 1 = 0x41 = ?
#channel 2 = 0x42 = ?
#channel 3 = 0x43 = poti

pin = int(sys.argv[1])
delay = int(sys.argv[2])

json_template = { 'poti': 0, 'light': 0, 'time': str(datetime.datetime.now().time()) }

def setup():
    ADC.setup(pin)

def loop():
    while True:

        json_template['time'] = str(datetime.datetime.now().time())
        json_template['poti'] = ADC.read(3)
        json_template['light'] = ADC.read(0)

        print json.dumps(json_template)
        sys.stdout.flush()

        time.sleep(delay)

if __name__ == "__main__":
    setup()
    loop()