#!/usr/bin/env python
from acdcdriver import pcf8591 as ADC
import time
import json
import sys
import datetime

#channel 0 = 0x40 = licht
#channel 1 = 0x41 = ?
#channel 2 = 0x42 = ?
#channel 3 = 0x43 = poti

json_template = { 'poti': 0, 'light': 0, 'time': str(datetime.datetime.now().time()) }

def setup():
	ADC.setup(0x48)

def loop():
	while True:

		if False:
			print "---------------------------"
			for i in range(4):
				print i, ADC.read(i)
				ADC.write(ADC.read(i))

		json_template['time'] = str(datetime.datetime.now().time())
		json_template['poti'] = ADC.read(3)
		json_template['light'] = ADC.read(0)
		print json.dumps(json_template)
		sys.stdout.flush()

		time.sleep(2.0)

if __name__ == "__main__":
	setup()
	loop()
