#!/usr/bin/python
# Info - This program is for PIN sensor. Contionusly checks for state,
#        set LED if movement detected and plays wav file on detection.

import RPi.GPIO as GPIO
import time
import datetime
import json
import sys

pin = int(sys.argv[1])
delay = int(sys.argv[2])

val = False
json_template = { 'state': 0, 'time': str(datetime.datetime.now().time()) }

GPIO.setmode(GPIO.BOARD)	# Change this if using GPIO numbering
GPIO.setup(pin, GPIO.IN, pull_up_down=GPIO.PUD_DOWN)	# Set PIN as input

try:
	while True:
		val = GPIO.input(pin)

		if (val == False):
			json_template['state'] = 1
		else:
			json_template['state'] = 0

		json_template['time'] = str(datetime.datetime.now().time())

		print json.dumps(json_template)
		sys.stdout.flush()
		time.sleep(delay)
except:
	GPIO.cleanup()