#!/usr/bin/python
import RPi.GPIO as GPIO
import time

LED = 13

GPIO.setmode(GPIO.BOARD)
GPIO.setup(LED, GPIO.OUT)
GPIO.setup(LED, GPIO.LOW)

dauer = 0.5

for x in range(10):
	GPIO.output(LED,GPIO.HIGH)
	time.sleep(dauer)
	GPIO.output(LED,GPIO.LOW)
	time.sleep(dauer)
	
GPIO.cleanup()
