#!/bin/bash
args=("$@")
LED_LIB_BASE=${args[0]}
SONG_NAME=${args[1]}
LED_COUNT=${args[2]}
VOLUME=${args[3]}

echo setting volume to $VOLUME
amixer set PCM -- $VOLUME
echo LED Base Library Location $LED_LIB_BASE
echo Playing song $SONG_NAME
echo LED count $LED_COUNT
export SYNCHRONIZED_LIGHTS_HOME="/opt/lightshow/lightshowpi"
export PYTHONPATH=$PYTHONPATH:$LED_LIB_BASE
/opt/lightshow/lightshowpi/py/synchronized_lights.py --ledcount $LED_COUNT --file "$SONG_NAME"