#!/bin/bash
args=("$@")
MODE=${args[0]}

if [ "$MODE" == "stop" ]; then
    KILL_PID=${args[1]}
    echo "killing $KILL_PID"
    kill -SIGINT -$KILL_PID
    exit
elif [ "$MODE" == "start" ]; then
    LED_LIB_BASE=${args[1]}
    SONG_NAME=${args[2]}
    LED_COUNT=${args[3]}
    VOLUME=${args[4]}
    echo "starting with $LED_LIB_BASE"
    echo setting volume to $VOLUME
    amixer set PCM -- $VOLUME
    echo LED Base Library Location $LED_LIB_BASE
    echo Playing song $SONG_NAME
    echo LED count $LED_COUNT
    export SYNCHRONIZED_LIGHTS_HOME="/opt/lightshow/lightshowpi"
    export PYTHONPATH=$PYTHONPATH:$LED_LIB_BASE
    /opt/lightshow/lightshowpi/py/synchronized_lights.py --ledcount $LED_COUNT --file "$SONG_NAME"
else
    echo "invalid command"
    exit
fi